export function createBotState() {
  return {
    connected: false,
    authorized: false,
    running: false,
    contractType: "rise_fall",
    sizingMode: "fixed",
    botMode: "trend",

    token: "",
    balance: 0,
    sessionProfit: 0,
    peakProfit: 0,
    tradeCount: 0,
    wins: 0,
    losses: 0,
    lossStreak: 0,
    currentStake: 0.35,

    tradeInProgress: false,
    contractId: null,
    lastTradeTime: 0,
    pauseUntil: 0,
    blockedUntil: 0,

    ticks: [],
    emaFast: null,
    emaSlow: null,
    emaFastHistory: [],
    emaSlowHistory: [],

    recentTrades: [],
    lastSignalText: "-",
    lastTradeMeta: null,

    digitStats: {
      lastDigit: null,
      lastDigits: [],
      counts: { 0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0 },
      evenCount: 0,
      oddCount: 0,
      streakType: null,
      streakLength: 0,
      rolling50: [],
      rolling100: [],
      biasScore: 0,
      signal: "NO TRADE",
      mode: "observer",
      executableEnabled: false,
      tradeCooldownUntil: 0,
      sampleSize: 0,
      sampleTargetReached: false
    },

    settings: {
      market: "R_25",
      baseStake: 0.35,
      minStake: 0.35,
      maxStake: 1.0,
      winMultiplier: 1.05,
      lossMultiplier: 0.85,
      duration: 3,
      durationUnit: "t",
      currency: "USD",
      cooldownMs: 1200,
      stopLossPercent: 1,
      takeProfitPercent: 2,
      fastEmaLength: 5,
      slowEmaLength: 12,
      confirmTicks: 3,
      moveWindow: 5,
      warmupTicks: 18,
      emaGapThreshold: 0.018,
      microMoveThreshold: 0.004,
      pauseAfterLosses: 2,
      pauseSeconds: 45,
      maxLosses: 5,
      maxTrades: 35,
      reentryBlockSeconds: 30,
      peakDrawdownLock: 0.8,

      digitDuration: 1,
      digitDurationUnit: "t",
      digitSampleTarget: 100,
      digitBias50Threshold: 30,
      digitBias100Threshold: 58,
      digitTradeCooldownMs: 10000,
      digitMaxTradesPerSession: 3
    }
  };
}